/**
 * Every copy block sent to Gemma, with its FACTS sheet (written by hand from the code and the eval files on
 * 2026-10-06; the source of each fact is the constant or file named in the comment next to it).
 *
 * NOT in this list on purpose (see docs/COPY-BY-GEMMA.md "Not sent"):
 *  - Kevin's own lines: the home hero (chip, h1, paragraph, "Free for parents."), the problem band heading, its
 *    two paragraphs and the two park verdicts, the how-it-works headline, the header nav labels, and the lines he
 *    wrote in his home copy reference that shipped as he wrote them ("Proof in every clue.", "See a real pass,
 *    right now.", "Print the pass. Pocket the pencil. Leave the phone.", "Make your first pass free").
 *  - Numbers-only or legal text: eval tables and stat tiles, the privacy table, licences and credits, the report
 *    rule, the October box dates, the progress-step labels (they mirror the server's real steps).
 *  - The folded technical details on /how-it-works and /about (dense numbers mixed with markup: a rewrite
 *    could only lose facts).
 *  - Text owned by files another builder is editing (src/lib/ai/**).
 *  - The printed kid pass and its safety lines (fixed to fit one page; safety wording is code-owned).
 */
import type { CopyBlock } from "./check.mts";

const GEMMA = "The AI model is Gemma 4 (gemma-4-31B-it), Google's open-weight model (Apache-2.0), run on DigitalOcean serverless inference in the US.";
const CHECKS = "Code checks every clue against its source and removes any that fail; the model never decides what is safe.";
const WAIT = "A new pass usually takes 10-30 seconds (PASS_WAIT_COPY), up to about a minute and a half when the free map websites are slow.";
const AGES = "Age bands are exactly 4-6, 6-10 and 10-13 (AGE_BAND_INFO).";
const SIGNIN = "Browsing, examples, shared links and printing need no sign-in. A NEW pass needs a grown-up signed in: 2 new passes a day each (ACCOUNT_PASSES_PER_DAY), reset at midnight Dallas time.";
const NODATA = 'Missing data is never faked: the site says "No data available" and why.';

const HOME = "/ (home)";
const HOW = "/how-it-works";
const ABOUT = "/about";
const SIGN = "/signin + sign-in card";
const PASS = "/pass/[id] and its print page";
const ERR = "messages (errors, limits, empty states)";

export const BLOCKS: readonly CopyBlock[] = [
  // ---------------- home ----------------
  {
    id: "home.how.link",
    page: HOME,
    file: "src/components/home/HowItWorks.tsx",
    role: "link under the How it works headline, to the long explainer page; 12 words or fewer",
    maxChars: 80,
    text: "The full story for curious grown-ups: the data, the AI and every check",
    facts: ["The linked page (/how-it-works) explains the data sources, what the AI does, and every check code runs."],
  },
  {
    id: "home.how.s1.title",
    page: HOME,
    file: "src/components/home/HowItWorks.tsx",
    role: "step 1 card title, 5 words or fewer",
    maxChars: 30,
    text: "Pick a park & age",
    facts: ["Step 1: the parent picks a park and the kid's age band."],
  },
  {
    id: "home.how.s1.body",
    page: HOME,
    file: "src/components/home/HowItWorks.tsx",
    role: "step 1 card body, 2 short sentences",
    maxChars: 170,
    text: "Type a town, ZIP or park name, or tap Use my location. Then pick 4–6, 6–10 or 10–13: it sets how many clues and how hard.",
    facts: [
      'Search by town, ZIP or park name, or the "Use my location" button.',
      AGES,
      "The age band sets how many finds (6, 8 or 8) and how hard the words are.",
    ],
    keep: ["Use my location", "4–6", "6–10", "10–13"],
  },
  {
    id: "home.how.s2.title",
    page: HOME,
    file: "src/components/home/HowItWorks.tsx",
    role: "step 2 card title, 5 words or fewer; must say AI",
    maxChars: 30,
    text: "AI builds the hunt",
    facts: ["Step 2: the AI model picks the finds and writes the clues; code checks them."],
    keep: ["AI"],
  },
  {
    id: "home.how.s2.body",
    page: HOME,
    file: "src/components/home/HowItWorks.tsx",
    role: "step 2 card body, 3-4 short sentences",
    maxChars: 260,
    text: "Gemma writes, code checks. Gemma 4 picks a fair mix from the park’s real map and 14 days of nearby sightings, then writes the clues. Code checks each one against its source. Usually 10–30 seconds.",
    facts: [GEMMA, "It works from the park's real OpenStreetMap map and the last 14 days of nearby iNaturalist wildlife sightings.", CHECKS, WAIT],
    keep: ["Gemma 4", "14 days", "10–30 seconds"],
  },
  {
    id: "home.how.s3.title",
    page: HOME,
    file: "src/components/home/HowItWorks.tsx",
    role: "step 3 card title, 5 words or fewer",
    maxChars: 30,
    text: "Print the page",
    facts: ["Step 3: print the one page."],
  },
  {
    id: "home.how.s3.body",
    page: HOME,
    file: "src/components/home/HowItWorks.tsx",
    role: "step 3 card body, 1-2 short sentences",
    maxChars: 170,
    text: "One black-and-white Letter page: the kid’s pass on top, a tear line, and a grown-up stub with the answers and sources.",
    facts: ["The pass is one black-and-white US Letter page.", "Top: the kid's pass. Then a tear line. Bottom: the grown-up's stub with the answers and sources."],
    keep: ["Letter"],
  },
  {
    id: "home.how.s4.title",
    page: HOME,
    file: "src/components/home/HowItWorks.tsx",
    role: "step 4 card title, 5 words or fewer",
    maxChars: 30,
    text: "Hide the phone",
    facts: ["Step 4: the phone goes away; the hunt is on paper."],
  },
  {
    id: "home.how.s4.body",
    page: HOME,
    file: "src/components/home/HowItWorks.tsx",
    role: "step 4 card body, 1-2 short sentences, light humor welcome",
    maxChars: 150,
    text: "Phone away. Your kid ticks off finds with a pencil; you keep the stub, in case anyone needs a hint.",
    facts: ["The kid ticks boxes with a pencil.", "The grown-up keeps the stub (answers), useful for hints."],
  },
  {
    id: "home.pass.sub",
    page: HOME,
    file: "src/components/home/PassAnatomy.tsx",
    role: 'subhead under "Proof in every clue.", 2 sentences, one light joke allowed',
    maxChars: 170,
    text: "Every clue comes from a real, dated source, listed on the grown-up's stub. So nobody spends 40 minutes hunting for a heron that flew off in 2019.",
    facts: ["Every clue comes from a real, dated source.", "The sources are listed on the grown-up's stub.", "The heron joke is Kevin's: no real heron, it is humor."],
  },
  {
    id: "home.pass.wild.body",
    page: HOME,
    file: "src/components/home/PassAnatomy.tsx",
    role: "Wild Finds card body, 2-3 sentences",
    maxChars: 240,
    text: "Real sightings of birds, bugs and blooms: plants and animals people photographed in or near the park (within 1.5 km) in the last 14 days. Gemma must quote each one's source, and code checks the quote word for word.",
    facts: [
      "Wild Finds are iNaturalist research-grade sightings within 1.5 km of the park in the last 14 days (WILD_RADIUS_KM, WILD_WINDOW_DAYS).",
      "People photographed them.",
      "Gemma must quote each find's source text; code checks the quote word for word.",
    ],
    keep: ["1.5 km", "14 days", "Gemma", "word for word"],
  },
  {
    id: "home.pass.wild.safety",
    page: HOME,
    file: "src/components/home/PassAnatomy.tsx",
    role: 'safety note after the bold label "Safety built in.", 2 sentences',
    maxChars: 170,
    text: "Venomous snakes, poison ivy, stinging bugs and more ({blocked} risky groups in all) are never printed. Every Wild Find says “look, don't touch.”",
    facts: [
      "{blocked} is the number of blocked risky species groups (BLOCKED_TAXA.length, 17 on 2026-10-06), filled in by code.",
      "Blocked: venomous snakes, poison ivy, stinging bugs and more. They are never printed.",
      'Every Wild Find carries the line "look, don\'t touch."',
    ],
    keep: ["never printed", "look, don't touch"],
  },
  {
    id: "home.pass.park.body",
    page: HOME,
    file: "src/components/home/PassAnatomy.tsx",
    role: "Park Finds card body, 1-2 sentences",
    maxChars: 170,
    text: "Hoops, shelters, bridges and playground gear, straight from the park's OpenStreetMap map, with real counts like “2 basketball courts.”",
    facts: ["Park Finds are things mapped inside the park on OpenStreetMap: hoops, shelters, bridges, playground gear.", "Code writes the real counts, for example \"2 basketball courts\"."],
    keep: ["OpenStreetMap", "2 basketball courts"],
  },
  {
    id: "home.pass.lucky.body",
    page: HOME,
    file: "src/components/home/PassAnatomy.tsx",
    role: "Lucky Finds card body, 2-3 sentences",
    maxChars: 240,
    text: "Maybe-sightings, like a dog or a bike, backed by at least 3 Google Maps reviews from the last 2 years that mention them (counted via SerpApi). No proof, no Lucky Finds: the pass leaves them off and says why.",
    facts: [
      "Lucky Finds are maybe-sightings (a dog, a bike) that at least 3 Google Maps reviews from the last 2 years mention (MIN_MENTIONS, WINDOW_MONTHS).",
      "Code counts the reviews through SerpApi; review text is never shown or sent to the AI.",
      "Without enough reviews the pass leaves Lucky Finds off and says why.",
      "Lucky Finds are NOT rare or bonus points.",
    ],
    keep: ["3", "2 years", "SerpApi", "Google Maps"],
  },
  {
    id: "home.pass.spot.body",
    page: HOME,
    file: "src/components/home/PassAnatomy.tsx",
    role: "Find This Spot card body, 2 short sentences",
    maxChars: 150,
    text: "Code draws a small black-and-white map of the park with a START and an X. Gemma writes a riddle about the spot.",
    facts: ["Code (not AI) draws a small black-and-white map of the park with START and an X.", "Gemma writes a riddle about the spot at the X."],
    keep: ["START", "X", "Gemma"],
  },
  {
    id: "home.pass.october.body",
    page: HOME,
    file: "src/components/home/PassAnatomy.tsx",
    role: "October monarch box card body, 2 short sentences",
    maxChars: 160,
    text: "Code counts monarchs reported nearby in the last 14 days, next to the same days last year. Printed honestly, even when it's zero.",
    facts: ["Code (no AI) counts monarch butterflies reported nearby in the last 14 days, next to the same days last year.", "The box prints the real count even when it is zero."],
    keep: ["14 days", "last year"],
  },
  {
    id: "home.explore.sub",
    page: HOME,
    file: "src/components/home/SampleParks.tsx",
    role: "subhead under \"See a real pass, right now.\", 2 short sentences",
    maxChars: 150,
    text: "Passes for parks near Dallas, already written from live park data for {ages}. Tap one to open it; no sign-up needed.",
    facts: ["The example parks are near Dallas.", "{ages} is the age band, filled in by code (ages 6–10).", "The passes are already made from live park data.", "Opening one needs no sign-up."],
    keep: ["Dallas", "no sign-up"],
  },
  {
    id: "home.explore.live.making",
    page: HOME,
    file: "src/lib/home/showcase.ts",
    role: "status pill, 7 words or fewer",
    maxChars: 50,
    text: "Making today's example passes now",
    facts: ["Shown while the server is making today's example passes."],
  },
  {
    id: "home.explore.live.off",
    page: HOME,
    file: "src/lib/home/showcase.ts",
    role: "status pill, 8 words or fewer",
    maxChars: 55,
    text: "Example passes are switched off on this server",
    facts: ["Shown when this server has example passes switched off (PREWARM_EXAMPLES=0)."],
  },
  {
    id: "home.explore.live.notready",
    page: HOME,
    file: "src/lib/home/showcase.ts",
    role: "status pill, 6 words or fewer",
    maxChars: 45,
    text: "Example passes not ready yet",
    facts: ["Shown when no example pass is ready yet."],
  },
  {
    id: "home.chips.lead",
    page: HOME,
    file: "src/components/home/ExampleChips.tsx",
    role: "phone-only lead-in before a row of example-park buttons, ends with a colon, 7 words or fewer",
    maxChars: 40,
    text: "Just looking? Open a real pass:",
    facts: ["The buttons after it open real example passes."],
  },
  {
    id: "home.card.stub",
    page: HOME,
    file: "src/components/home/HeroPassCard.tsx",
    role: "tiny caption on the example pass card's tear-off stub, 6 words or fewer",
    maxChars: 40,
    text: "Grown-up's stub · answers & safety",
    facts: ["The bottom part of a pass is the grown-up's stub with the answers and safety notes."],
  },
  {
    id: "home.card.open",
    page: HOME,
    file: "src/components/home/HeroPassCard.tsx",
    role: "tiny link, 3 words or fewer",
    maxChars: 20,
    text: "Open this pass",
    facts: ["Opens the real example pass shown on the card."],
  },
  {
    id: "home.hero.sticker",
    page: HOME,
    file: "src/components/home/HomeHero.tsx",
    role: "sticker on the hero picture, 4 words or fewer",
    maxChars: 22,
    text: "Fits on 1 page",
    facts: ["A pass prints on one page."],
    keep: ["1"],
  },
  {
    id: "home.cta.sub",
    page: HOME,
    file: "src/components/home/FinalCta.tsx",
    role: "subhead under the final call to action, 1 sentence",
    maxChars: 120,
    text: "Free, one printable page, written for the park across the street, not some park somewhere else.",
    facts: ["A pass is free.", "It is one printable page.", "It is written for the specific park you pick."],
    keep: ["Free"],
  },
  {
    id: "home.parks.connemara.big",
    page: HOME,
    file: "src/components/home/TwoParks.tsx",
    role: "label under the big number 70, 12 words or fewer",
    maxChars: 75,
    text: "kinds of plants and animals spotted in and around it in 2 weeks",
    facts: ["Connemara Meadow: 70 kinds (species) of plants and animals, iNaturalist research-grade sightings within 1.5 km, last 14 days, measured Oct 5, 2026.", "Starts lowercase: it reads on from the number."],
    keep: ["2 weeks"],
  },
  {
    id: "home.parks.connemara.small",
    page: HOME,
    file: "src/components/home/TwoParks.tsx",
    role: "label under the small number 0, 6 words or fewer",
    maxChars: 40,
    text: "playgrounds, courts or shelters",
    facts: ["Connemara Meadow has 0 playgrounds, courts or shelters mapped on OpenStreetMap.", "Starts lowercase: it reads on from the number."],
  },
  {
    id: "home.parks.celebration.big",
    page: HOME,
    file: "src/components/home/TwoParks.tsx",
    role: "label under the big number 25, 8 words or fewer",
    maxChars: 50,
    text: "soccer fields mapped here, plus 6 courts",
    facts: ["Celebration Park: 25 soccer fields and 6 courts mapped on OpenStreetMap, measured Oct 5, 2026.", "Starts lowercase: it reads on from the number."],
    keep: ["6 courts"],
  },
  {
    id: "home.parks.celebration.small",
    page: HOME,
    file: "src/components/home/TwoParks.tsx",
    role: "label under the small number 0, 5 words or fewer",
    maxChars: 35,
    text: "recent wildlife sightings",
    facts: ["Celebration Park had 0 research-grade wildlife sightings in the last 14 days.", "Starts lowercase: it reads on from the number."],
  },
  {
    id: "footer.about",
    page: "footer (every page)",
    file: "src/components/SiteFooter.tsx",
    role: "footer link to /about, 4 words or fewer",
    maxChars: 25,
    text: "About Grass Pass",
    facts: ["Links to the About page."],
  },
  {
    id: "footer.how",
    page: "footer (every page)",
    file: "src/components/SiteFooter.tsx",
    role: "footer link to /how-it-works, 4 words or fewer",
    maxChars: 25,
    text: "How Grass Pass works",
    facts: ["Links to the How it works page."],
  },
  {
    id: "meta.home.description",
    page: "site meta + OG (every page)",
    file: "src/app/layout.tsx",
    role: "meta description / social share text, 2-3 sentences",
    maxChars: 250,
    text: "A free one-page treasure hunt for your local park. Gemma 4, an open-weight AI model, reads that park's real map and the last 14 days of wildlife sightings and writes the clues. Code checks every one. Print it, and the phone stays in your pocket.",
    facts: [GEMMA, "It reads the park's real OpenStreetMap map and the last 14 days of iNaturalist sightings.", CHECKS, "Free, one printable page."],
    keep: ["Gemma 4", "14 days"],
  },

  // ---------------- /how-it-works ----------------
  {
    id: "how.meta.title",
    page: HOW,
    file: "src/app/how-it-works/page.tsx",
    role: "browser tab / share title, 12 words or fewer, starts with \"How Grass Pass works\"",
    maxChars: 75,
    text: "How Grass Pass works: real park data in, one open model, paper out",
    facts: ["Real park data goes in, one open model (Gemma 4) writes, a paper pass comes out."],
    keep: ["How Grass Pass works"],
  },
  {
    id: "how.meta.description",
    page: HOW,
    file: "src/app/how-it-works/page.tsx",
    role: "meta description, 2-3 sentences",
    maxChars: 260,
    text: "Step by step: how Grass Pass turns one park's real map and recent wildlife sightings into a printable kids' pass. Gemma 4, an open model, writes the clues; code fact-checks every one. What the AI does and doesn't do, and what we measured.",
    facts: [GEMMA, CHECKS, "The page shows what the AI does and doesn't do, and the measured results (misses included)."],
    keep: ["Gemma 4"],
  },
  {
    id: "how.h1",
    page: HOW,
    file: "src/app/how-it-works/page.tsx",
    role: "page headline, 7 words or fewer, ends with a full stop",
    maxChars: 45,
    text: "How a park becomes a pass.",
    facts: ["The page explains how one real park becomes a printed pass."],
  },
  {
    id: "how.lead",
    page: HOW,
    file: "src/app/how-it-works/page.tsx",
    role: "lead paragraph under the headline, 3-4 short sentences",
    maxChars: 230,
    text: "You pick the park. Gemma 4, an open AI model, writes the clues from its real map and the last two weeks of wildlife sightings. Code fact-checks every one. Your printer does the rest.",
    facts: [GEMMA, "Sources: the park's real map (OpenStreetMap) and the last 14 days of wildlife sightings (iNaturalist).", CHECKS],
    keep: ["Gemma 4"],
  },
  {
    id: "how.quick.title",
    page: HOW,
    file: "src/app/how-it-works/page.tsx",
    role: "section headline (the 30-second version), 8 words or fewer",
    maxChars: 50,
    text: "Pick a park. Print a pass. Phone away.",
    facts: ["The short version: pick a park, print a pass, put the phone away."],
  },
  {
    id: "how.quick.1.title",
    page: HOW,
    file: "src/app/how-it-works/page.tsx",
    role: "card title, 5 words or fewer",
    maxChars: 30,
    text: "Pick a park & age",
    facts: ["Pick a real park and the kid's age band."],
  },
  {
    id: "how.quick.1.body",
    page: HOW,
    file: "src/app/how-it-works/page.tsx",
    role: "card body, 1 sentence",
    maxChars: 100,
    text: "A real park near you, plus your kid's age: 4-6, 6-10 or 10-13.",
    facts: [AGES],
    keep: ["4-6", "6-10", "10-13"],
  },
  {
    id: "how.quick.2.title",
    page: HOW,
    file: "src/app/how-it-works/page.tsx",
    role: "card title, 5 words or fewer",
    maxChars: 30,
    text: "We read the park",
    facts: ["Code collects the park's real data."],
  },
  {
    id: "how.quick.2.body",
    page: HOW,
    file: "src/app/how-it-works/page.tsx",
    role: "card body, 1 sentence",
    maxChars: 120,
    text: "Its map, the last {days} days of wildlife sightings nearby, and what visitor reviews mention.",
    facts: ["{days} is filled in by code (WILD_WINDOW_DAYS = 14).", "Data: the park's map (OpenStreetMap), nearby wildlife sightings (iNaturalist), and what Google Maps reviews mention (counts only, via SerpApi)."],
  },
  {
    id: "how.quick.3.title",
    page: HOW,
    file: "src/app/how-it-works/page.tsx",
    role: "card title, 5 words or fewer; must say AI",
    maxChars: 30,
    text: "AI writes, code checks",
    facts: ["The AI writes; code checks."],
    keep: ["AI"],
  },
  {
    id: "how.quick.3.body",
    page: HOW,
    file: "src/app/how-it-works/page.tsx",
    role: "card body, 2 sentences",
    maxChars: 160,
    text: "Gemma 4, an open model, picks a fair mix and writes kid-sized clues. Code checks each one, and asks once more if too many fail.",
    facts: [GEMMA, CHECKS, "If too many clues fail, code asks the model again (a pass makes at most 3 model calls, MAX_MODEL_CALLS)."],
    keep: ["Gemma 4", "asks again"],
  },
  {
    id: "how.quick.4.title",
    page: HOW,
    file: "src/app/how-it-works/page.tsx",
    role: "card title, 5 words or fewer",
    maxChars: 30,
    text: "Print, phone away",
    facts: ["Print it and put the phone away."],
  },
  {
    id: "how.quick.4.body",
    page: HOW,
    file: "src/app/how-it-works/page.tsx",
    role: "card body, 1-2 short sentences",
    maxChars: 100,
    text: "One page. The kid takes the hunt; you keep the answer key.",
    facts: ["One printed page: the kid's hunt on top, the grown-up's answer key below."],
  },
  {
    id: "how.quick.note",
    page: HOW,
    file: "src/app/how-it-works/page.tsx",
    role: "small note under the 4 cards, 2 sentences, one light joke allowed",
    maxChars: 170,
    text: 'A new pass usually takes 10-30 seconds, about as long as finding the other shoe. A section with no data says "No data available" and why.',
    facts: [WAIT, NODATA],
    keep: ["10-30 seconds"],
  },
  {
    id: "how.steps.title",
    page: HOW,
    file: "src/app/how-it-works/page.tsx",
    role: "section headline, 8 words or fewer",
    maxChars: 45,
    text: "From “which park?” to “found it!”",
    facts: ["The section walks through every step from choosing a park to finding things."],
  },
  {
    id: "how.steps.intro",
    page: HOW,
    file: "src/app/how-it-works/page.tsx",
    role: "intro paragraph, 2 sentences",
    maxChars: 190,
    text: "Each step says who does it: code (the same result every time), the open model, or you. The AI has one job: picking the finds and writing the words.",
    facts: ["Each step is labelled code, the open model, or you.", "Code gives the same result every time.", "The AI's only job: picking the finds and writing the words."],
  },
  {
    id: "how.step.park.title",
    page: HOW,
    file: "src/app/how-it-works/page.tsx",
    role: "step title, 5 words or fewer",
    maxChars: 35,
    text: "Find the park",
    facts: ["Step 1 (code): find the park."],
  },
  {
    id: "how.step.park.summary",
    page: HOW,
    file: "src/app/how-it-works/page.tsx",
    role: "step summary, 2 sentences",
    maxChars: 190,
    text: "Type a town, ZIP or park name, or tap Use my location (we round it to about 1 km). Code lists the parks within 5 km, from OpenStreetMap.",
    facts: ["Search by town, ZIP or park name, or Use my location.", "Your location is rounded to about 1 km in your browser.", "Code lists parks within 5 km from OpenStreetMap."],
    keep: ["Use my location", "1 km", "5 km", "OpenStreetMap"],
  },
  {
    id: "how.step.data.title",
    page: HOW,
    file: "src/app/how-it-works/page.tsx",
    role: "step title, 6 words or fewer",
    maxChars: 40,
    text: "Gather what's really there",
    facts: ["Step 2 (code): collect what is really in and near the park."],
  },
  {
    id: "how.step.data.summary",
    page: HOW,
    file: "src/app/how-it-works/page.tsx",
    role: "step summary, 1-2 sentences",
    maxChars: 200,
    text: "Code fills three lists, each fact dated and sourced: Park Finds (OpenStreetMap), Wild Finds (iNaturalist, Wikipedia) and Lucky Finds (review counts via SerpApi).",
    facts: ["Code fills three lists; each fact has a date and a source.", "Park Finds: OpenStreetMap. Wild Finds: iNaturalist and Wikipedia. Lucky Finds: Google review counts via SerpApi."],
    keep: ["Park Finds", "Wild Finds", "Lucky Finds", "OpenStreetMap", "iNaturalist", "Wikipedia", "SerpApi"],
  },
  {
    id: "how.step.safety.title",
    page: HOW,
    file: "src/app/how-it-works/page.tsx",
    role: "step title, 9 words or fewer, light humor welcome",
    maxChars: 55,
    text: "Take out anything that bites, stings or itches",
    facts: ["Step 3 (code): remove risky species."],
  },
  {
    id: "how.step.safety.summary",
    page: HOW,
    file: "src/app/how-it-works/page.tsx",
    role: "step summary, 1-2 sentences",
    maxChars: 170,
    text: "Code removes {blocked} blocked groups of risky species (think fire ants and poison ivy) before the model sees the list, and checks again after.",
    facts: ["{blocked} is filled in by code (17 groups on 2026-10-06).", "Examples: fire ants, poison ivy.", "Removed before the model sees the list, and checked again after."],
    keep: ["before", "after"],
  },
  {
    id: "how.step.model.title",
    page: HOW,
    file: "src/app/how-it-works/page.tsx",
    role: "step title, 6 words or fewer",
    maxChars: 40,
    text: "The open model writes the clues",
    facts: ["Step 4 (the open model): write the clues."],
  },
  {
    id: "how.step.model.summary",
    page: HOW,
    file: "src/app/how-it-works/page.tsx",
    role: "step summary, 3 short sentences",
    maxChars: 260,
    text: "Code sends the park's fact list to {model} on DigitalOcean serverless inference. It picks the finds by id and writes a clue and a proof quote for each, plus one riddle. Usually that is one call; step 6 is the exception.",
    facts: [
      "{model} is filled in by code: the model id, plus \"(Google's Gemma 4, open weights, Apache-2.0)\" when it is Gemma.",
      "It runs on DigitalOcean serverless inference.",
      "The model picks finds by id, writes a clue and a proof quote for each, plus one riddle.",
      "Usually one call; step 6 (retry or refills, at most 3 calls) is the exception.",
    ],
    keep: ["DigitalOcean", "step 6"],
  },
  {
    id: "how.step.checks.title",
    page: HOW,
    file: "src/app/how-it-works/page.tsx",
    role: "step title, 5 words or fewer",
    maxChars: 35,
    text: "Code fact-checks every clue",
    facts: ["Step 5 (code): check every clue."],
  },
  {
    id: "how.step.checks.summary",
    page: HOW,
    file: "src/app/how-it-works/page.tsx",
    role: "step summary, 2 sentences",
    maxChars: 240,
    text: "Code never takes the AI's word for it. It removes any clue that breaks one of {always} hard rules (proof quote, name leaks, numbers, safety), and swaps out clues that miss {softer} style rules when it can.",
    facts: ["{always} and {softer} are rule counts filled in by code.", "Hard rules: proof quote, name leaks, numbers, safety. A clue that breaks one is removed.", "Clues that miss a style rule are swapped out when a spare can replace them."],
    keep: ["hard rules", "style rules"],
  },
  {
    id: "how.step.retry.title",
    page: HOW,
    file: "src/app/how-it-works/page.tsx",
    role: "step title, 6 words or fewer",
    maxChars: 40,
    text: "Refill once, or print it short",
    facts: ["Step 6 (code): ask once more, or print a shorter pass."],
  },
  {
    id: "how.step.retry.summary",
    page: HOW,
    file: "src/app/how-it-works/page.tsx",
    role: "step summary, 3 short sentences",
    maxChars: 190,
    text: "Too few clues survive? Code asks the model once more for the missing ones. Still short? The pass says how many are missing. No made-up filler.",
    facts: ["If too few clues pass, code asks the model again for the missing ones (at most 3 model calls per pass, MAX_MODEL_CALLS).", "If still short, the pass says how many finds are missing.", "Nothing is padded with made-up finds."],
    keep: ["again"],
  },
  {
    id: "how.step.spot.title",
    page: HOW,
    file: "src/app/how-it-works/page.tsx",
    role: "step title, 7 words or fewer",
    maxChars: 45,
    text: "Find This Spot and the October box",
    facts: ["Step 7 (code): the Find This Spot map and the October box."],
    keep: ["Find This Spot", "October box"],
  },
  {
    id: "how.step.spot.summary",
    page: HOW,
    file: "src/app/how-it-works/page.tsx",
    role: "step summary, 2 sentences",
    maxChars: 150,
    text: "Code picks a landmark, draws a map with an X and measures the walk. The October box is all code.",
    facts: ["Code picks a landmark, draws a map with an X and measures the walk.", "The October monarch box is all code (no AI)."],
    keep: ["October box"],
  },
  {
    id: "how.step.print.title",
    page: HOW,
    file: "src/app/how-it-works/page.tsx",
    role: "step title, 5 words or fewer",
    maxChars: 35,
    text: "Print it, hide the phone",
    facts: ["Step 8 (you): print it and put the phone away."],
  },
  {
    id: "how.step.print.summary",
    page: HOW,
    file: "src/app/how-it-works/page.tsx",
    role: "step summary, 2 sentences, light humor welcome",
    maxChars: 160,
    text: "One black-and-white page: the kid's hunt on top, your answer key and sources below. Then the phone goes in the bag.",
    facts: ["One black-and-white page: the kid's hunt on top, the grown-up's answer key and sources below."],
  },
  {
    id: "how.step.cache.title",
    page: HOW,
    file: "src/app/how-it-works/page.tsx",
    role: "step title, 5 words or fewer",
    maxChars: 35,
    text: "Saving work, and fair limits",
    facts: ["Step 9 (code): saved passes and fair limits."],
  },
  {
    id: "how.step.cache.summary",
    page: HOW,
    file: "src/app/how-it-works/page.tsx",
    role: "step summary, 2 sentences",
    maxChars: 190,
    text: "Passes are saved for 30 days. A new pass needs a grown-up signed in ({perDay} a day); daily limits protect the model budget and the free map servers.",
    facts: ["Passes are saved for 30 days.", "{perDay} is filled in by code (2 new passes a day per grown-up).", "Daily limits protect the model budget and the free map servers."],
    keep: ["30 days"],
  },
  {
    id: "how.ai.title",
    page: HOW,
    file: "src/app/how-it-works/page.tsx",
    role: "section headline, 9 words or fewer; must say AI",
    maxChars: 55,
    text: "The AI picks and writes. Code does the rest.",
    facts: ["The AI picks finds and writes words; code does everything else."],
    keep: ["AI"],
  },
  {
    id: "how.ai.does.1",
    page: HOW,
    file: "src/app/how-it-works/page.tsx",
    role: 'bullet under "The AI does", 8 words or fewer, starts with a verb',
    maxChars: 50,
    text: "Pick the finds, inside the mix code allows.",
    facts: ["The AI picks the finds within the mix code allows."],
  },
  {
    id: "how.ai.does.2",
    page: HOW,
    file: "src/app/how-it-works/page.tsx",
    role: 'bullet under "The AI does", 8 words or fewer, starts with a verb',
    maxChars: 50,
    text: "Write each clue in kid words, plus a hint.",
    facts: ["The AI writes each clue in kid-level words, plus an optional hint."],
  },
  {
    id: "how.ai.does.3",
    page: HOW,
    file: "src/app/how-it-works/page.tsx",
    role: 'bullet under "The AI does", 8 words or fewer, starts with a verb',
    maxChars: 50,
    text: "Rate each find easy, medium or hard.",
    facts: ["The AI rates each find easy, medium or hard."],
  },
  {
    id: "how.ai.does.4",
    page: HOW,
    file: "src/app/how-it-works/page.tsx",
    role: 'bullet under "The AI does", 8 words or fewer, starts with a verb',
    maxChars: 50,
    text: "Copy a proof quote from its facts.",
    facts: ["The AI copies a proof quote from each find's facts (code checks it word for word)."],
  },
  {
    id: "how.ai.does.5",
    page: HOW,
    file: "src/app/how-it-works/page.tsx",
    role: 'bullet under "The AI does", 8 words or fewer, starts with a verb',
    maxChars: 50,
    text: "Write the Find This Spot riddle.",
    facts: ["The AI writes the Find This Spot riddle."],
    keep: ["Find This Spot"],
  },
  {
    id: "how.code.does.1",
    page: HOW,
    file: "src/app/how-it-works/page.tsx",
    role: 'bullet under "Code does", 8 words or fewer, starts with a verb',
    maxChars: 50,
    text: "Collect every fact, with its source and date.",
    facts: ["Code collects every fact with its source and date."],
  },
  {
    id: "how.code.does.2",
    page: HOW,
    file: "src/app/how-it-works/page.tsx",
    role: 'bullet under "Code does", 8 words or fewer, starts with a verb',
    maxChars: 50,
    text: "Remove unsafe species, before and after.",
    facts: ["Code removes unsafe species before and after the model."],
    keep: ["before", "after"],
  },
  {
    id: "how.code.does.3",
    page: HOW,
    file: "src/app/how-it-works/page.tsx",
    role: 'bullet under "Code does", 8 words or fewer, starts with a verb',
    maxChars: 50,
    text: "Set the mix and the number of finds.",
    facts: ["Code sets the section mix and the number of finds."],
  },
  {
    id: "how.code.does.4",
    page: HOW,
    file: "src/app/how-it-works/page.tsx",
    role: 'bullet under "Code does", 8 words or fewer, starts with a verb',
    maxChars: 50,
    text: "Check every clue; remove failures.",
    facts: ["Code checks every clue and removes the ones that fail."],
  },
  {
    id: "how.code.does.5",
    page: HOW,
    file: "src/app/how-it-works/page.tsx",
    role: 'bullet under "Code does", 9 words or fewer, starts with a verb',
    maxChars: 55,
    text: "Pick the spot, draw the map, measure the walk.",
    facts: ["Code picks the Find This Spot place, draws the map and measures the walk."],
  },
  {
    id: "how.code.does.6",
    page: HOW,
    file: "src/app/how-it-works/page.tsx",
    role: 'bullet under "Code does", 9 words or fewer, starts with a verb',
    maxChars: 55,
    text: "Write every number, date, safety line and answer.",
    facts: ["Code writes every number, date, safety line and answer on the pass."],
  },
  {
    id: "how.ai.schema",
    page: HOW,
    file: "src/app/how-it-works/page.tsx",
    role: "one sentence under the two lists",
    maxChars: 110,
    text: "The AI can't invent a find: its answer's schema only allows ids from the park's own list.",
    facts: ["The model's JSON answer schema only allows ids from the park's own fact list, so it cannot invent a find."],
  },
  {
    id: "how.open.title",
    page: HOW,
    file: "src/app/how-it-works/page.tsx",
    role: "section headline, 6 words or fewer",
    maxChars: 40,
    text: "Open weights, our own rules",
    facts: ["Gemma 4's weights are open; the rules live in our code."],
  },
  {
    id: "how.open.1.title",
    page: HOW,
    file: "src/app/how-it-works/page.tsx",
    role: "card title, 5 words or fewer",
    maxChars: 30,
    text: "The licence is open.",
    facts: ["Gemma 4's licence is Apache-2.0."],
  },
  {
    id: "how.open.1.body",
    page: HOW,
    file: "src/app/how-it-works/page.tsx",
    role: "card body, 1 sentence",
    maxChars: 100,
    text: "Gemma 4's weights are Apache-2.0: anyone can download, run and build on them.",
    facts: ["Gemma 4's weights are Apache-2.0: anyone can download, run and build on them."],
    keep: ["Gemma 4", "Apache-2.0"],
  },
  {
    id: "how.open.2.title",
    page: HOW,
    file: "src/app/how-it-works/page.tsx",
    role: "card title, 5 words or fewer",
    maxChars: 30,
    text: "It can be self-hosted.",
    facts: ["The app can talk to a self-hosted model server."],
  },
  {
    id: "how.open.2.body",
    page: HOW,
    file: "src/app/how-it-works/page.tsx",
    role: "card body, 2 short sentences; must give the measured self-host result",
    // RULES-6-02 (Builder AA): room for both results (the app's normal limits, and more time).
    maxChars: 150,
    text: "Any OpenAI-compatible server works, such as Ollama on your computer. Not measured yet.",
    // Fact fix after the self-host measurement (Builder W, 2026-10-06, evals/results/2026-10-06-selfhost-notes.md).
    facts: [
      "Any OpenAI-compatible server works, for example Ollama on your own computer.",
      "Measured: Gemma 4 E2B on a laptop CPU costs $0 but takes 1-3 minutes a pass, too slow for the app's 70 s limit.",
      // RULES-6-02: the 1-3 minutes need more time than the app's normal limits give.
      "With the app's normal time limits, 0 of 5 passes finished complete; given more time (the eval's longer clock), a pass takes 1-3 minutes.",
    ],
    keep: ["OpenAI-compatible", "Ollama", "$0", "0 of 5"],
  },
  {
    id: "how.open.3.title",
    page: HOW,
    file: "src/app/how-it-works/page.tsx",
    role: "card title, 5 words or fewer",
    maxChars: 30,
    text: "Our rules, not a vendor's.",
    facts: ["The safety and truth rules are in our code, not a model vendor's."],
  },
  {
    id: "how.open.3.body",
    page: HOW,
    file: "src/app/how-it-works/page.tsx",
    role: "card body, 1 sentence",
    maxChars: 110,
    text: "The same checks run on any model; Llama 4 Maverick went through them in our test.",
    facts: ["The same checks run on any model.", "Llama 4 Maverick was run through the same checks in our eval."],
    keep: ["Llama 4 Maverick"],
  },
  {
    id: "how.limits.title",
    page: HOW,
    file: "src/app/how-it-works/page.tsx",
    role: "section headline, 6 words or fewer",
    maxChars: 40,
    text: "What doesn’t work (yet)",
    facts: ["The section lists the app's honest limits."],
  },
  {
    id: "how.privacy.title",
    page: HOW,
    file: "src/app/how-it-works/page.tsx",
    role: "section headline, 5 words or fewer",
    maxChars: 35,
    text: "Nothing about your child",
    facts: ["Nothing about the child is asked for or sent."],
  },
  {
    id: "how.built.title",
    page: HOW,
    file: "src/app/how-it-works/page.tsx",
    role: "section headline, 9 words or fewer",
    maxChars: 60,
    text: "Built in the contest week, with AI coding agents",
    facts: ["Built during the contest week with AI coding agents (Claude Code)."],
  },
  {
    id: "how.built.body",
    page: HOW,
    file: "src/app/how-it-works/page.tsx",
    role: "short paragraph, 2 sentences",
    maxChars: 200,
    text: "Built during the Hacktoberfest 2026 Week 1 entry period (first commit Oct 5, 2026). Kevin made the decisions; AI coding agents wrote and reviewed most of the code.",
    facts: ["Built during the Hacktoberfest 2026 Week 1 entry period; first commit Oct 5, 2026.", "Kevin made the decisions; AI coding agents wrote and reviewed most of the code."],
    keep: ["Hacktoberfest 2026 Week 1", "Oct 5, 2026", "Kevin"],
  },
  {
    id: "how.privacy.1",
    page: HOW,
    file: "src/lib/about/content.ts",
    role: "privacy bullet, 1-2 short sentences",
    maxChars: 90,
    text: "No names, no photos, no analytics. Browsing and printing set no cookie.",
    facts: ["No names, no photos, no analytics.", "Browsing and printing set no cookie."],
    keep: ["no cookie"],
  },
  {
    id: "how.privacy.3",
    page: HOW,
    file: "src/lib/about/content.ts",
    role: "privacy bullet, 1 sentence",
    maxChars: 100,
    text: "What you type goes to our server and OpenStreetMap, never into the web address.",
    facts: ["What you type goes to our server and OpenStreetMap (Nominatim), never into the web address."],
    keep: ["OpenStreetMap", "web address"],
  },
  {
    id: "how.privacy.4",
    page: HOW,
    file: "src/lib/about/content.ts",
    role: "privacy bullet, 1 sentence",
    maxChars: 80,
    text: "\"Use my location\" is rounded to about 1 km in your browser.",
    facts: ['"Use my location" is rounded to about 1 km in your browser before it is sent.'],
    keep: ["Use my location", "1 km", "browser"],
  },
  {
    id: "how.privacy.5",
    page: HOW,
    file: "src/lib/about/content.ts",
    role: "privacy bullet, 1 sentence",
    maxChars: 90,
    text: "The model sees the park's public facts and the age band, nothing about you.",
    facts: ["The model gets the park's public facts and the age band, nothing about you or your child."],
    keep: ["age band"],
  },

  // ---------------- /about ----------------
  {
    id: "about.meta.title",
    page: ABOUT,
    file: "src/app/about/page.tsx",
    role: "browser tab / share title, 12 words or fewer, starts with \"About Grass Pass\"",
    maxChars: 70,
    text: "About Grass Pass: an open model, a real park and a pencil",
    facts: ["Grass Pass: an open AI model, a real park, a pencil."],
    keep: ["About Grass Pass"],
  },
  {
    id: "about.meta.description",
    page: ABOUT,
    file: "src/app/about/page.tsx",
    role: "meta description, 2-3 sentences",
    maxChars: 280,
    text: "Gemma 4, an open-weight model, writes each Grass Pass from one park's real data: OpenStreetMap, iNaturalist, Wikipedia and Google review counts (SerpApi). Code checks every clue. What we measured (misses included), what leaves your device, and every credit.",
    facts: [GEMMA, "Data: OpenStreetMap, iNaturalist, Wikipedia and Google review counts via SerpApi.", CHECKS, "The page shows what we measured (misses included), what leaves your device, and every credit."],
    keep: ["Gemma 4", "OpenStreetMap", "iNaturalist", "Wikipedia", "SerpApi"],
  },
  {
    id: "about.h1",
    page: ABOUT,
    file: "src/app/about/page.tsx",
    role: "page headline, 9 words or fewer, ends with a full stop",
    maxChars: 50,
    text: "An open model, a real park and a pencil.",
    facts: ["Grass Pass = an open AI model + a real park + a pencil."],
  },
  {
    id: "about.lead",
    page: ABOUT,
    file: "src/app/about/page.tsx",
    role: "lead paragraph, 3-4 short sentences",
    maxChars: 220,
    text: "A one-page treasure hunt for a real park. Gemma 4, an open-weight model, writes clues from its map and recent wildlife sightings. Code checks each one. The finding happens on paper.",
    facts: [GEMMA, "Sources: the park's map and recent wildlife sightings.", CHECKS, "One printed page; the hunt happens on paper."],
    keep: ["Gemma 4"],
  },
  {
    id: "about.howlink",
    page: ABOUT,
    file: "src/app/about/page.tsx",
    role: "primary button to /how-it-works, 8 words or fewer",
    maxChars: 45,
    text: "See how a pass is made, step by step",
    facts: ["Links to the step-by-step How it works page."],
  },
  {
    id: "about.measured.title",
    page: ABOUT,
    file: "src/app/about/page.tsx",
    role: "section headline, 5 words or fewer",
    maxChars: 30,
    text: "Measured, not promised.",
    facts: ["The numbers below are measured in a real eval run; misses are shown."],
  },
  {
    id: "about.inside.title",
    page: ABOUT,
    file: "src/app/about/page.tsx",
    role: "section headline, 7 words or fewer",
    maxChars: 45,
    text: "Open model. Real data. Rules in code.",
    facts: ["An open model, real data, and rules enforced in code."],
  },
  {
    id: "about.model.title",
    page: ABOUT,
    file: "src/app/about/page.tsx",
    role: "card title, 6 words or fewer",
    maxChars: 35,
    text: "Gemma 4 writes the clues",
    facts: [GEMMA],
    keep: ["Gemma 4"],
  },
  {
    id: "about.whyopen.1",
    page: ABOUT,
    file: "src/lib/about/content.ts",
    role: "check-mark bullet, 1 sentence",
    maxChars: 70,
    text: "Anyone can download, run and build on the weights.",
    facts: ["Gemma 4's weights are open (Apache-2.0): anyone can download, run and build on them."],
  },
  {
    id: "about.whyopen.2",
    page: ABOUT,
    file: "src/lib/about/content.ts",
    role: "check-mark bullet, 1 sentence",
    maxChars: 70,
    text: "Our safety rules live in our code, not a vendor's.",
    facts: ["The safety rules are in our code, not a model vendor's."],
  },
  {
    id: "about.whyopen.3",
    page: ABOUT,
    file: "src/lib/about/content.ts",
    role: "check-mark bullet, 1 sentence; must give the measured self-host result",
    maxChars: 70,
    text: "Self-hosting is possible, but not measured yet.",
    // Fact fix after the self-host measurement (Builder W, 2026-10-06, evals/results/2026-10-06-selfhost-notes.md).
    facts: ["Measured: self-hosted on a laptop CPU, a pass costs $0 but is slow (too slow for the app's 70 s limit)."],
    keep: ["$0", "slow"],
  },
  {
    id: "about.data.title",
    page: ABOUT,
    file: "src/app/about/page.tsx",
    role: "card title, 5 words or fewer",
    maxChars: 30,
    text: "Four real sources, dated",
    facts: ["Four real data sources (OpenStreetMap, iNaturalist, Wikipedia, SerpApi), each fact dated."],
  },
  {
    id: "about.data.osm",
    page: ABOUT,
    file: "src/lib/about/content.ts",
    role: "one-line description of a data source (OpenStreetMap), 8 words or fewer",
    maxChars: 50,
    text: "Parks, paths and what is mapped inside them",
    facts: ["OpenStreetMap gives the parks, their paths and what is mapped inside them."],
  },
  {
    id: "about.data.inat",
    page: ABOUT,
    file: "src/lib/about/content.ts",
    role: "one-line description of a data source (iNaturalist), 8 words or fewer",
    maxChars: 50,
    text: "Wildlife people really spotted nearby",
    facts: ["iNaturalist gives wildlife people really photographed nearby (research-grade)."],
  },
  {
    id: "about.data.wiki",
    page: ABOUT,
    file: "src/lib/about/content.ts",
    role: "one-line description of a data source (Wikipedia), 8 words or fewer",
    maxChars: 50,
    text: "A short fact about each species",
    facts: ["Wikipedia gives a short summary of each species."],
  },
  {
    id: "about.data.serp",
    page: ABOUT,
    file: "src/lib/about/content.ts",
    role: "one-line description of a data source (SerpApi), 10 words or fewer",
    maxChars: 60,
    text: "How often Google Maps reviews mention dogs or bikes",
    facts: ["SerpApi gives counts of how often Google Maps reviews mention things like dogs or bikes (counts only, no review text)."],
    keep: ["Google Maps"],
  },
  {
    id: "about.data.nodata",
    page: ABOUT,
    file: "src/app/about/page.tsx",
    role: "small note, 2 short sentences; must keep the quoted words",
    maxChars: 80,
    text: 'No data? The pass says "No data available" and why. Never padded.',
    facts: [NODATA, "Passes are never padded with generic items."],
  },
  {
    id: "about.safety.title",
    page: ABOUT,
    file: "src/app/about/page.tsx",
    role: "card title, 4 words or fewer",
    maxChars: 25,
    text: "Safety by code",
    facts: ["Safety is enforced by code, not the AI."],
  },
  {
    id: "about.safety.1",
    page: ABOUT,
    file: "src/app/about/page.tsx",
    role: "bullet, 1 sentence",
    maxChars: 90,
    text: "{blocked} risky groups are never printed, checked before and after the model.",
    facts: ["{blocked} is filled in by code (17 groups on 2026-10-06).", "Blocked groups are never printed; checked before and after the model."],
    keep: ["never printed", "before and after"],
  },
  {
    id: "about.safety.2",
    page: ABOUT,
    file: "src/app/about/page.tsx",
    role: "bullet, 1 sentence",
    maxChars: 60,
    text: "Every clue must quote its source word for word.",
    facts: ["Every clue must quote its source word for word (code checks)."],
    keep: ["word for word"],
  },
  {
    id: "about.safety.3",
    page: ABOUT,
    file: "src/app/about/page.tsx",
    role: "bullet, 1 sentence",
    maxChars: 60,
    text: "Every number, date and safety line is written by code.",
    facts: ["Code writes every number, date and safety line."],
  },
  {
    id: "about.privacy.1",
    page: ABOUT,
    file: "src/lib/about/content.ts",
    role: "privacy check-mark bullet, 1 short sentence",
    maxChars: 60,
    text: "Browsing and printing need no account or cookie.",
    facts: ["Browsing and printing need no account and set no cookie."],
  },
  {
    id: "about.privacy.2",
    page: ABOUT,
    file: "src/lib/about/content.ts",
    role: "privacy check-mark bullet, 1 sentence",
    maxChars: 85,
    text: "Sign-in only to make a new pass; we keep a scrambled ID, no email or name.",
    facts: ["Sign-in is needed only to make a new pass (or report).", "We keep only a scrambled ID: no email, no name."],
    keep: ["scrambled ID"],
  },
  {
    id: "about.privacy.3",
    page: ABOUT,
    file: "src/lib/about/content.ts",
    role: "privacy check-mark bullet, 1 short sentence",
    maxChars: 50,
    text: "Nothing about your child is asked for.",
    facts: ["Nothing about the child is asked for."],
  },
  {
    id: "about.privacy.4",
    page: ABOUT,
    file: "src/lib/about/content.ts",
    role: "privacy check-mark bullet, 1 short sentence",
    maxChars: 55,
    text: "Your location is rounded to about 1 km first.",
    facts: ["Your location is rounded to about 1 km before it leaves your browser."],
    keep: ["1 km"],
  },
  {
    id: "about.privacy.5",
    page: ABOUT,
    file: "src/lib/about/content.ts",
    role: "privacy check-mark bullet, 1 short sentence",
    maxChars: 55,
    text: "Your IP is kept only scrambled, for about a day.",
    facts: ["Your IP address is kept only as a keyed hash (scrambled), in counters that expire within about a day."],
    keep: ["a day"],
  },
  {
    id: "about.privacy.6",
    page: ABOUT,
    file: "src/lib/about/content.ts",
    role: "privacy check-mark bullet, 1 short sentence",
    maxChars: 55,
    text: "Park facts and age band go to the model (US).",
    facts: ["The park's facts and the age band are sent to the model, which runs in the US (DigitalOcean)."],
    keep: ["US"],
  },
  {
    id: "about.limit.4",
    page: ABOUT,
    file: "src/lib/about/content.ts",
    role: "limit bullet, 1 short sentence",
    maxChars: 60,
    text: "The read-it-as-a-7-year-old check is not done yet.",
    facts: ["A check where clues are read as a 7-year-old would is planned, NOT done yet."],
    keep: ["7", "not done yet"],
  },
  {
    id: "about.limit.5",
    page: ABOUT,
    file: "src/lib/about/content.ts",
    role: "limit bullet, 1 short sentence",
    maxChars: 60,
    text: "Find This Spot and Lucky Finds are not in the eval yet.",
    facts: ["Find This Spot and Lucky Finds were not part of the eval run yet."],
    keep: ["Find This Spot", "Lucky Finds"],
  },
  {
    id: "about.details.title",
    page: ABOUT,
    file: "src/app/about/page.tsx",
    role: "section headline, 5 words or fewer",
    maxChars: 35,
    text: "Details, one click away.",
    facts: ["The details are folded and open with one click."],
  },
  {
    id: "about.privacy.note2",
    page: ABOUT,
    file: "src/lib/about/content.ts",
    role: "paragraph under the privacy table, 1 sentence",
    maxChars: 120,
    text: "The model runs on DigitalOcean's servers in the US, so the park facts and the age band do leave your device.",
    facts: ["The model runs on DigitalOcean's servers in the US.", "The park facts and the age band leave your device."],
    keep: ["DigitalOcean", "US"],
  },
  {
    id: "about.privacy.note3",
    page: ABOUT,
    file: "src/lib/about/content.ts",
    role: "paragraph under the privacy table, 1 sentence",
    maxChars: 130,
    text: "Our logs record which source or model ran, timing, outcome and pass id; never the prompt, your IP or what you typed.",
    facts: ["Logs record which source or model ran, timing, outcome and pass id.", "Logs never record the prompt, your IP or what you typed."],
    keep: ["never"],
  },

  // ---------------- sign-in ----------------
  {
    id: "signin.err.rate",
    page: SIGN,
    file: "src/lib/accounts/signin-errors.ts",
    role: "error message, 2 sentences",
    maxChars: 120,
    text: "Whoa, that's a lot of sign-in attempts from your connection. Please wait a few minutes and try again.",
    facts: ["Too many sign-in attempts from this connection; wait a few minutes and try again."],
  },
  {
    id: "signin.err.unavailable",
    page: SIGN,
    file: "src/lib/accounts/signin-errors.ts",
    role: "error message, 2 short sentences",
    maxChars: 100,
    text: "That sign-in option isn't set up on this server. Pick another one below.",
    facts: ["That sign-in option isn't set up on this server; other options are below."],
  },
  {
    id: "signin.err.denied",
    page: SIGN,
    file: "src/lib/accounts/signin-errors.ts",
    role: "error message, 2 short sentences",
    maxChars: 100,
    text: "Sign-in was cancelled, so nothing changed. Changed your mind? Try again below.",
    facts: ["Sign-in was cancelled; nothing changed. You can try again below."],
  },
  {
    id: "signin.err.callback",
    page: SIGN,
    file: "src/lib/accounts/signin-errors.ts",
    role: "error message, 1-2 short sentences",
    maxChars: 80,
    text: "The sign-in page didn't finish loading. Please try again.",
    facts: ["The provider's sign-in page didn't finish; try again."],
  },
  {
    id: "signin.err.config",
    page: SIGN,
    file: "src/lib/accounts/signin-errors.ts",
    role: "error message, 2 sentences",
    maxChars: 120,
    text: "Sign-in isn't set up correctly on this server right now. The examples and saved passes still work.",
    facts: ["Sign-in is misconfigured on this server right now.", "Examples and saved passes still work without sign-in."],
  },
  {
    id: "signin.err.verify",
    page: SIGN,
    file: "src/lib/accounts/signin-errors.ts",
    role: "error message, 2 short sentences",
    maxChars: 70,
    text: "That sign-in link didn't work. Please try again.",
    facts: ["The sign-in link didn't work; try again."],
  },
  {
    id: "signin.err.general",
    page: SIGN,
    file: "src/lib/accounts/signin-errors.ts",
    role: "error message, 1-2 short sentences",
    maxChars: 70,
    text: "Sign-in didn't work this time. Please give it another try.",
    facts: ["Sign-in failed for an unknown reason; try again."],
  },
  {
    id: "signin.page.heading",
    page: SIGN,
    file: "src/app/signin/page.tsx",
    role: "card heading on the sign-in page, 12 words or fewer",
    maxChars: 70,
    text: "Sign in to make new passes and tell us what you found",
    facts: ["Signing in lets a grown-up make new passes and report what they found."],
  },
  {
    id: "signin.why.1",
    page: SIGN,
    file: "src/app/signin/page.tsx",
    role: 'bullet under "Why sign in?", 2 sentences',
    maxChars: 140,
    text: "Only to make a new pass (2 a day) or to tell us what you found. Examples, shared links and printing work without it.",
    facts: [SIGNIN, "Signed-in grown-ups can also report what they found."],
    keep: ["2 a day"],
  },
  {
    id: "signin.privacy.link",
    page: SIGN,
    file: "src/app/signin/page.tsx",
    role: "link to the privacy section, 12 words or fewer, light humor welcome",
    maxChars: 70,
    text: "What we keep (spoiler: very little), and for how long",
    facts: ["Links to the About page privacy section: what is kept and for how long."],
  },
  {
    id: "signin.card.body",
    page: SIGN,
    file: "src/components/account/SignInCard.tsx",
    role: "sign-in card paragraph, 2-3 sentences, before a sentence code adds",
    maxChars: 180,
    text: "Each new pass wakes up a real AI model, so a grown-up signs in first: 2 new passes a day each. Examples and saved passes need no sign-in.",
    facts: ["Each new pass is a real (paid) AI model call.", SIGNIN],
    keep: ["AI", "2 new passes a day"],
  },
  {
    id: "signin.judge.unknown",
    page: SIGN,
    file: "src/components/account/SignInCard.tsx",
    role: "status line, 1 sentence",
    maxChars: 80,
    text: "We couldn't check how many judge passes are left today right now.",
    facts: ["Shown when the count of judge passes left today can't be read."],
  },
  {
    id: "account.privacy",
    page: SIGN,
    file: "src/lib/accounts/config.ts",
    role: "privacy line on the sign-in card and pages, 2 sentences",
    maxChars: 120,
    text: "We only keep a scrambled ID to count your 2 passes a day and your found-it reports. No email, no name.",
    facts: ["We keep only a scrambled ID, to count your 2 passes a day and your reports.", "No email, no name."],
    keep: ["scrambled ID", "2 passes a day", "No email, no name"],
  },
  {
    id: "account.grownups",
    page: SIGN,
    file: "src/lib/accounts/config.ts",
    role: "1 short sentence",
    maxChars: 60,
    text: "Sign-in is for parents and teachers, not kids.",
    facts: ["Sign-in is for grown-ups (parents and teachers), not kids."],
  },
  {
    id: "account.limit",
    page: SIGN,
    file: "src/lib/accounts/config.ts",
    role: "limit message, 2 sentences",
    maxChars: 170,
    text: "That's your {n} new passes for today. Your passes and the examples still work, and you get {n} more after midnight (Dallas time).",
    facts: ["{n} is filled in by code (2).", "Your saved passes and the examples still work.", "New passes again after midnight Dallas time."],
    keep: ["midnight", "Dallas time"],
  },
  {
    id: "account.judgeNote",
    page: SIGN,
    file: "src/lib/accounts/config.ts",
    role: "note under the judge button, 1 sentence",
    maxChars: 95,
    text: "Try as a judge signs you in to a shared demo account: no sign-up, nothing to type.",
    facts: ['"Try as a judge" signs you in to a shared demo account: no sign-up, nothing to type.'],
    keep: ["Try as a judge", "shared demo account"],
  },
  {
    id: "account.notConfigured",
    page: SIGN,
    file: "src/lib/accounts/config.ts",
    role: "message, 2 sentences",
    maxChars: 130,
    text: "Sign-in isn't set up on this server yet, so it can't make new passes. The examples and saved passes still work.",
    facts: ["This server has no sign-in set up, so it can't make new passes.", "Examples and saved passes still work."],
  },
  {
    id: "maker.signedin",
    page: HOME,
    file: "src/components/pass/PassMaker.tsx",
    role: "screen-reader announcement after sign-in, 2 short sentences",
    maxChars: 50,
    text: "Signed in. You can make this pass now.",
    facts: ["The grown-up is now signed in and can make the pass."],
  },

  // ---------------- pass + print ----------------
  {
    id: "pass.printline",
    page: PASS,
    file: "src/app/pass/[id]/page.tsx",
    role: "line next to the Print pass button, 2 sentences",
    maxChars: 110,
    text: "One black-and-white page. Cut it in half: the kid gets the hunt, you get the answers.",
    facts: ["One black-and-white page.", "Cut in half: the kid gets the hunt, the grown-up gets the answers."],
  },
  {
    id: "pass.reports.in",
    page: PASS,
    file: "src/components/pass/PassPreview.tsx",
    role: "intro above the report buttons (signed in), 2 sentences",
    maxChars: 170,
    text: "Back from the park? Tap what you found. It helps the next family, and a find nobody can spot (or that isn't safe) gets left off new passes.",
    facts: ["Signed-in grown-ups tap Found it / Didn't find it / Not safe for each find.", "Reports help the next family: a find nobody can spot, or that isn't safe, is left off new passes for that park."],
  },
  {
    id: "report.thanks",
    page: PASS,
    file: "src/lib/reports/kinds.ts",
    role: "confirmation after a report, 3 words or fewer",
    maxChars: 25,
    text: "Thanks — counted.",
    facts: ["The report was counted."],
  },
  {
    id: "report.duplicate",
    page: PASS,
    file: "src/lib/reports/kinds.ts",
    role: "message, 2 short sentences",
    maxChars: 60,
    text: "You already reported this find today. Thanks!",
    facts: ["You already reported this find today, so it isn't counted twice."],
  },
  {
    id: "report.judgeLogged",
    page: PASS,
    file: "src/lib/reports/kinds.ts",
    role: "message, 2 sentences",
    maxChars: 110,
    text: "Thanks! Judge demo reports are logged for us to review, but they don't change passes or the counts.",
    facts: ["Judge demo reports are only logged for review; they never change passes or counts."],
  },
  {
    id: "report.judgeDuplicate",
    page: PASS,
    file: "src/lib/reports/kinds.ts",
    role: "message, 2 short sentences",
    maxChars: 80,
    text: "You already sent that one from this browser today. Try another find.",
    facts: ["This browser already sent that report today."],
  },
  {
    id: "print.lead",
    page: PASS,
    file: "src/app/pass/[id]/print/page.tsx",
    role: "screen-only instructions above the printable page, 3 short sentences; keep the print setting words exactly",
    maxChars: 200,
    text: 'Here\'s your pass: one Letter page, black and white. In the print box, pick {scale} (or "Default"). Then cut on the dashed line: the kid takes the hunt, you keep the answer key.',
    facts: ["{scale} is the bold words \"Scale: 100%\", filled in by code.", "One US Letter page, black and white.", "Cut on the dashed line: the kid takes the hunt, the grown-up keeps the answer key."],
    keep: ["Letter", '"Default"', "dashed line"],
  },
  {
    id: "stub.cutline",
    page: PASS,
    file: "src/components/pass/ParentStub.tsx",
    role: "tiny printed text on the cut line, 11 words or fewer",
    maxChars: 60,
    text: "cut here · kid keeps the top, grown-up keeps the bottom",
    facts: ["Cut here: the kid keeps the top, the grown-up keeps the bottom."],
  },
  {
    id: "notfound.body",
    page: ERR,
    file: "src/app/not-found.tsx",
    role: "404 page text, 2 sentences, light humor welcome",
    maxChars: 120,
    text: "There's no page at this address (maybe a typo). Good news: the parks are right where you left them.",
    facts: ["There is no page at this address."],
  },
  {
    id: "passgone.lead",
    page: ERR,
    file: "src/app/pass/[id]/not-found.tsx",
    role: "1 short sentence before the fixed no-data line, light humor welcome",
    maxChars: 50,
    text: "This pass seems to have wandered off.",
    facts: ["The pass isn't here."],
  },
  {
    id: "pass.allEmpty",
    page: ERR,
    file: "src/lib/pass/schema.ts",
    role: 'empty state, 2 sentences, starts with "No data available for {park}"',
    maxChars: 170,
    text: "No data available for {park} yet: no mapped features and no recent wildlife sightings. Try a bigger park nearby from the list.",
    facts: ["{park} is filled in by code.", "The park has no mapped features and no recent wildlife sightings.", "Suggest a bigger park nearby from the list."],
    keep: ["No data available for {park}"],
  },
  {
    id: "pass.notAPark",
    page: ERR,
    file: "src/lib/pass/schema.ts",
    role: "error, 2 short sentences",
    maxChars: 90,
    text: "We couldn't read that park on OpenStreetMap. Pick another park from the list.",
    facts: ["The park couldn't be read on OpenStreetMap; pick another from the list."],
    keep: ["OpenStreetMap"],
  },
  {
    id: "pass.paused",
    page: ERR,
    file: "src/lib/pass/schema.ts",
    role: "limit message, 2 sentences",
    maxChars: 110,
    text: "Clue writing is paused for today (free budget used). Passes already made today still work.",
    facts: ["The daily model budget is used, so no new clues today.", "Passes already made today still work."],
  },
  {
    id: "pass.variantLimit",
    page: ERR,
    file: "src/lib/pass/schema.ts",
    role: "limit message, 2 sentences",
    maxChars: 170,
    text: "That's {max} different passes for this park and age today, the most we make. Print one of them, pick another park, or come back tomorrow.",
    facts: ["{max} is filled in by code (3 different passes per park, age band and day).", "Options: print one, pick another park, or come back tomorrow."],
  },
  {
    id: "parks.noPlace",
    page: ERR,
    file: "src/lib/parks/schema.ts",
    role: "search error, 2 short sentences",
    maxChars: 70,
    text: "We couldn't find that place. Try a town name or ZIP.",
    facts: ["The place search found nothing; try a town name or ZIP."],
  },
  {
    id: "parks.geocoderDown",
    page: ERR,
    file: "src/lib/parks/schema.ts",
    role: 'empty state, starts with "No data available:", 2 sentences',
    maxChars: 120,
    text: "No data available: the map search isn't answering. Try 'Use my location' or an example park.",
    facts: ["The map search (Nominatim) isn't answering.", "Use my location or an example park still work."],
    keep: ["Use my location"],
  },
  {
    id: "parks.noParks",
    page: ERR,
    file: "src/lib/parks/schema.ts",
    role: "empty state, 1 sentence",
    maxChars: 60,
    text: "No parks found within 5 km in OpenStreetMap.",
    facts: ["No parks within 5 km in OpenStreetMap."],
    keep: ["5 km", "OpenStreetMap"],
  },
  {
    id: "parks.overpassDown",
    page: ERR,
    file: "src/lib/parks/schema.ts",
    role: 'empty state, starts with "No data available:", 2 sentences; no fixed wait time',
    maxChars: 120,
    text: "No data available: the OpenStreetMap server is busy. Try again shortly, or pick an example park.",
    facts: ["The OpenStreetMap (Overpass) server is busy.", "Try again shortly or pick an example park. Do not promise a wait time."],
    keep: ["OpenStreetMap"],
  },
  {
    id: "parks.busyHere",
    page: ERR,
    file: "src/lib/parks/schema.ts",
    role: "message, 2 short sentences",
    maxChars: 90,
    text: "Grass Pass is busy with other park lookups right now. Try again in a few seconds.",
    facts: ["Grass Pass's own lookup slots are busy (not OpenStreetMap's fault); try again in a few seconds."],
  },
  {
    id: "parks.parkTooBig",
    page: ERR,
    file: "src/lib/parks/schema.ts",
    role: 'empty state, starts with "No data available:", 2 sentences',
    maxChars: 120,
    text: "No data available: OpenStreetMap couldn't read this park in time (it may be very big). Try a smaller park nearby.",
    facts: ["OpenStreetMap couldn't read this park in time; it may be very big.", "Try a smaller park nearby."],
    keep: ["OpenStreetMap"],
  },
  {
    id: "parks.savedIndex",
    page: ERR,
    file: "src/lib/parks/schema.ts",
    role: "notice above a park list, 2 sentences",
    maxChars: 200,
    text: "The OpenStreetMap park server didn't answer in time, so this list comes from our saved copy of OpenStreetMap parks around Dallas (see the date below). New parks may be missing.",
    facts: ["The live OpenStreetMap park server didn't answer in time.", "This list is our saved copy of OpenStreetMap parks around Dallas; its date is shown below.", "New parks may be missing."],
    keep: ["OpenStreetMap", "Dallas", "date below"],
  },
  {
    id: "parks.nominatimParks",
    page: ERR,
    file: "src/lib/parks/schema.ts",
    role: "notice above a park list, 2 sentences",
    maxChars: 180,
    text: "The OpenStreetMap park server didn't answer in time, so this list comes from the OpenStreetMap place search (Nominatim) instead. It may miss some parks.",
    facts: ["The live OpenStreetMap park server didn't answer in time.", "This list comes from the OpenStreetMap place search (Nominatim) instead; it may miss some parks."],
    keep: ["OpenStreetMap", "Nominatim"],
  },
  {
    id: "find.noGeo",
    page: ERR,
    file: "src/components/parks/FindAPark.tsx",
    role: "error, 2 short sentences",
    maxChars: 75,
    text: "Your browser can't share a location. Type a town or ZIP instead.",
    facts: ["This browser can't share a location; type a town or ZIP."],
  },
  {
    id: "find.geoDenied",
    page: ERR,
    file: "src/components/parks/FindAPark.tsx",
    role: "error, 2 sentences",
    maxChars: 120,
    text: "Location is blocked for this site. Type a town or ZIP instead, or allow location in your browser settings.",
    facts: ["Location is blocked for this site; type a town or ZIP, or allow location in browser settings."],
  },
  {
    id: "find.geoFailed",
    page: ERR,
    file: "src/components/parks/FindAPark.tsx",
    role: "error, 2 short sentences",
    maxChars: 75,
    text: "We couldn't get your location. Try again, or type a town or ZIP.",
    facts: ["Getting the location failed; try again or type a town or ZIP."],
  },
  {
    id: "find.offline",
    page: ERR,
    file: "src/components/parks/FindAPark.tsx",
    role: "error, 2 short sentences",
    maxChars: 90,
    text: "We couldn't reach Grass Pass. Check your internet connection and try again.",
    facts: ["The browser couldn't reach the Grass Pass server; check the connection and retry."],
  },
  {
    id: "find.slow",
    page: ERR,
    file: "src/components/parks/FindAPark.tsx",
    role: "status while waiting, 2 sentences",
    maxChars: 180,
    text: "Still working: the OpenStreetMap park server can be slow. If it doesn't answer soon, we use a saved park list or the OpenStreetMap place search instead.",
    facts: ["The OpenStreetMap park server can be slow.", "If it doesn't answer soon, the search falls back to a saved park list or the OpenStreetMap place search."],
    keep: ["OpenStreetMap"],
  },
  {
    id: "wait.copy",
    page: ERR,
    file: "src/components/pass/usePassRequest.ts",
    role: "status while a pass is made, 1 sentence",
    maxChars: 130,
    text: "A new pass usually takes 10-30 seconds, and up to about a minute and a half when the free map websites are slow.",
    facts: [WAIT],
    keep: ["10-30 seconds", "a minute and a half"],
  },
  {
    id: "wait.timeout",
    page: ERR,
    file: "src/components/pass/usePassRequest.ts",
    role: "error after the browser stops waiting, 3 sentences",
    maxChars: 260,
    text: "This is taking much longer than usual (over a minute and a half), so we stopped waiting. The free map and wildlife websites can be slow at busy times. Try again: if your pass got made in the meantime, it opens right away.",
    facts: ["The browser stopped waiting after about a minute and a half.", "The free map and wildlife websites can be slow at busy times.", "Retrying opens the pass at once if it was made in the meantime."],
    keep: ["a minute and a half"],
  },
  {
    id: "lucky.notConnected",
    page: ERR,
    file: "src/lib/pool/lucky.ts",
    role: 'section message on a pass, starts with "Lucky Finds: not connected.", 2 sentences',
    maxChars: 140,
    text: "Lucky Finds: not connected. This server has no SerpApi key, so there are no Lucky Finds from visitor reviews.",
    facts: ["This server has no SerpApi key, so no Lucky Finds from visitor reviews."],
    keep: ["Lucky Finds: not connected.", "SerpApi"],
  },
  {
    id: "lucky.dailyCap",
    page: ERR,
    file: "src/lib/pool/lucky.ts",
    role: 'section message on a pass, starts with "Lucky Finds: off for today.", 2 sentences',
    maxChars: 160,
    text: "Lucky Finds: off for today. Grass Pass has used its free search limit for visitor reviews (SerpApi); it resets at midnight Dallas time.",
    facts: ["The free daily SerpApi search limit is used; it resets at midnight Dallas time."],
    keep: ["Lucky Finds: off for today.", "SerpApi", "midnight Dallas time"],
  },
  {
    id: "lucky.down",
    page: ERR,
    file: "src/lib/pool/lucky.ts",
    role: 'section message, starts with "No data available:", 1 sentence',
    maxChars: 110,
    text: "No data available: Google reviews (via SerpApi) didn't answer, so there are no Lucky Finds on this pass.",
    facts: ["Google reviews via SerpApi didn't answer; no Lucky Finds on this pass."],
    keep: ["SerpApi", "Lucky Finds"],
  },
  {
    id: "wild.down",
    page: ERR,
    file: "src/lib/pool/wild.ts",
    role: 'section message, starts with "No data available:", 2 sentences',
    maxChars: 150,
    text: "No data available: iNaturalist (the wildlife sightings service) didn't answer when this pass was made. Trying again in a minute may help.",
    facts: ["iNaturalist (the wildlife sightings service) didn't answer when this pass was made.", "Trying again in a minute may help."],
    keep: ["iNaturalist", "in a minute"],
  },
  {
    id: "spot.noLandmark",
    page: ERR,
    file: "src/lib/spot/types.ts",
    role: 'section message, starts with "No Find This Spot today:", 1 sentence',
    maxChars: 100,
    text: "No Find This Spot today: this park has no single landmark on the map (OpenStreetMap).",
    facts: ["This park has no landmark it has only one of on OpenStreetMap, so no Find This Spot."],
    keep: ["No Find This Spot today:", "OpenStreetMap"],
  },
  {
    id: "spot.busy",
    page: ERR,
    file: "src/lib/spot/types.ts",
    role: 'section message, starts with "No Find This Spot today:", 2 sentences',
    maxChars: 130,
    text: "No Find This Spot today: the OpenStreetMap server was busy, so we couldn't draw the map. Make a different pass to try again.",
    facts: ["The OpenStreetMap server was busy, so the map couldn't be drawn.", 'Pressing "Make a different pass" tries again.'],
    keep: ["No Find This Spot today:", "OpenStreetMap", "Make a different pass"],
  },
  {
    id: "datatooslow",
    page: ERR,
    file: "src/lib/pass/park-data.ts",
    role: "error, 2 sentences",
    maxChars: 120,
    text: "The park data took too long to load, so there was no time left to write clues. Try again shortly.",
    facts: ["Park data took too long, leaving no time to write clues; try again shortly."],
  },
  {
    id: "showcase.nofinds",
    page: HOME,
    file: "src/lib/home/showcase.ts",
    role: 'example card line, starts with "No data available:", 1 sentence',
    maxChars: 80,
    text: "No data available: this pass has no finds that passed our checks.",
    facts: ["No find on this example pass passed the checks."],
  },

  // ---------------- README first screen ----------------
  {
    id: "readme.tagline",
    page: "README.md (first screen)",
    file: "README.md",
    role: "one-line tagline under the title, 12 words or fewer",
    maxChars: 70,
    text: "Your ticket to get outside. Pick a park. Print a pass. Phone away.",
    facts: ["Grass Pass: pick a park, print a pass, put the phone away. The logo line is \"Your ticket to get outside.\""],
    keep: ["Your ticket to get outside."],
  },
  {
    id: "readme.intro",
    page: "README.md (first screen)",
    file: "README.md",
    role: "intro paragraph for developers and judges, 5-6 sentences",
    maxChars: 640,
    text: "Grass Pass turns your local park into a one-page treasure hunt in about 30 seconds. Pick a park and your kid's age (4-6, 6-10 or 10-13). Code collects what is really in that park. Gemma 4 (open weights, Apache-2.0, on DigitalOcean) picks a fair mix and writes kid-level clues, usually in one call (plus one refill call if too few pass). Code then fact-checks every clue against its source, drops any that fail, and writes every number, date and safety line itself. You print one black-and-white page: the kid ticks boxes with a pencil; you keep a tear-off stub with the answers, safety notes and sources. The phone stays in your pocket.",
    facts: [
      GEMMA,
      AGES,
      "A pass usually takes 10-30 seconds (about 30 seconds).",
      // Fact fix (judge round 6, Builder AA): the slow cases, measured (README Limitations).
      "Up to about a minute and a half for a big park or a slow model (a judge's big-park pass took about 57 s plus an 11.6 s search).",
      "Usually one model call; at most 3 (one whole retry if the first call fails, refills if too few clues pass).",
      CHECKS,
      "Code writes every number, date and safety line.",
      "One black-and-white page; the kid ticks boxes with a pencil; the grown-up keeps a tear-off stub with answers, safety notes and sources.",
    ],
    keep: ["Gemma 4", "Apache-2.0", "DigitalOcean", "4-6", "6-10", "10-13", "30 seconds"],
  },
  {
    id: "readme.nodata",
    page: "README.md (first screen)",
    file: "README.md",
    role: "one sentence (bold markdown is added by code around the quoted words)",
    maxChars: 110,
    text: 'If a source has nothing, the pass says "No data available" and why. It never pads the pass with generic items.',
    facts: [NODATA, "Passes are never padded with generic items."],
  },
];
